version: "3.9"
services:
  juno:
    # user: "${UID}:${GID}" # default user within container
    image: local/jupyternotebookrocm:latest
    container_name: jupyternotebookrocm
    devices:
      - "/dev/kfd"
      - "/dev/dri"
    group_add: 
      - video
    ipc: host
    cap_add: 
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    # command: /miniconda/envs/juno/bin/jupyter notebook --allow-root --port=8888 --ip 0.0.0.0 --no-browser
    # command: /bin/sh -c "while sleep 1000; do :; done" # keep container open while running
    command: bash
    stdin_open: true
    tty: true
    ports: # Host:Container
      - "8888:8888" # Jupyter Notebook
      - "8889:8889" # Jupyter Notebook
    volumes:
      - type: bind
        source: ./notebooks
        target: /notebooks
      - type: bind
        source: ./
        target: /workspaces/jupyter-notebook-rocm # vscode workspace folder
      # store vscode extensions to avoid to reinstall every time the container is created anew
      - type: bind
        source: ./vscode-container-ext/.vscode-server
        target: /home/vscode/.vscode-server
      - type: bind
        source: ./vscode-container-ext/.vscode-server-insiders
        target: /home/vscode/.vscode-server-insiders